apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: bucktuality
type: Opaque
stringData:
  connection-string: >-
    Server=mssql,1433;
    Database=BucktualityUsersDb;
    User Id=sa;
    Password=Bucktuality@12345;
    TrustServerCertificate=True;
    Encrypt=False;