services:
  redis:
    image: redis:7
    container_name: bucktuality-redis
    ports:
      - "6379:6379"

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: bucktuality-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Bucktuality@12345"
    ports:
      - "1433:1433"
    volumes:
      - bucktuality-sql-data:/var/opt/mssql

volumes:
  bucktuality-sql-data: