apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-service
  namespace: bucktuality
spec:
  template:
    spec:
      containers:
        - name: session-service
          envFrom:
            - configMapRef:
                name: session-service-config
