apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bucktuality

resources:
  - ../../base

configMapGenerator:
  - name: admin-service-config
    envs:
      - config/admin-service.env

  - name: ai-moderation-service-config
    envs:
      - config/ai-moderation-service.env

  - name: analytics-service-config
    envs:
      - config/analytics-service.env

  - name: gateway-config
    envs:
      - config/gateway.env

  - name: matchmaking-service-config
    envs:
      - config/matchmaking-service.env

  - name: moderation-service-config
    envs:
      - config/moderation-service.env

  - name: notification-service-config
    envs:
      - config/notification-service.env

  - name: presence-service-config
    envs:
      - config/presence-service.env

  - name: realtime-service-config
    envs:
      - config/realtime-service.env

  - name: session-service-config
    envs:
      - config/session-service.env

  - name: user-service-config
    envs:
      - config/user-service.env

generatorOptions:
  disableNameSuffixHash: true

patches:
  - path: patches/admin-service-configmap.yaml
  - path: patches/ai-moderation-service-configmap.yaml
  - path: patches/analytics-service-configmap.yaml
  - path: patches/gateway-configmap.yaml
  - path: patches/matchmaking-service-configmap.yaml
  - path: patches/moderation-service-configmap.yaml
  - path: patches/notification-service-configmap.yaml
  - path: patches/presence-service-configmap.yaml
  - path: patches/realtime-service-configmap.yaml
  - path: patches/session-service-configmap.yaml
  - path: patches/user-service-configmap.yaml
